### ISSUE TITLE
Looking for TIA standard

### ISSUE THREAD

**Issue by raspberrydev** [omahacommsys/KFDtool#14]
Hi all, I've been wanting to contribute to this project, but don't have access to TIA-102.AACD. Is there any way somebody could share it with me? I'd like to dive into the specifics of the protocol.

Thank you in advance

**Comment by jelimoore** [comment]
No.

TIA-102 is a copyrighted suite of documents. It is against the law for me or anyone else to give them to you. Hope that answers your question.

Closing this issue.
