### ISSUE TITLE
Unable to load key containers via AES, receive Error-- invalid broadcast length

### ISSUE THREAD

**Issue by badellinger** [omahacommsys/KFDtool#17]
All CKRs and IDs match. I've tried restarting my computer. I've tried every release 32bit and 64bit. I've tried running as administrator. I've tried deleting and rebuilding keylists radio side, and I've tried deleting and rebuilding containers. Individual keys load fine, containers produce the error.

![Screenshot (1)](https://github.com/user-attachments/assets/3008b8fb-2c5f-46ed-97d1-8ed2a7f18078)

**Comment by Aglowgibbon** [comment]
This might have been fixed by @ilyacodes in the latest commit. He might be able to comment better on it.
