### ISSUE TITLE
VP600 issue

### ISSUE THREAD

**Issue by carcarjg** [omahacommsys/KFDtool#5]
Key Erase, Key Info, and Key load, all return invalid response length errors.
Keyset info just crashes the SW

Logs attached are from key Info operations on a VP600 with 5 DES keys loaded, and a XTS with 10 DES/DES-XL keys loaded
[XTS5000AppLog.txt](https://github.com/omahacommsys/KFDtool/files/10771469/XTS5000AppLog.txt)
[VP600AppLog.txt](https://github.com/omahacommsys/KFDtool/files/10771471/VP600AppLog.txt)

**Comment by duggerd** [comment]
What are the firmware and SEM versions of the VP600? What are the KFDShield firmware and software versions being used?

You shouldn't ever get an application crash like that though, did that have any associated log events?

**Comment by duggerd** [comment]
The VP600 might be more picky on the timing on the keyload interface and works with the KFDtool but not the KFDShield. I would need to look at the physical interface to know for sure though.

It has been reported previously that it works with the KFDtool from customer feedback.

https://github.com/KFDtool/KFDtool/blob/master/doc/RADIO_COMPATIBILITY.md#:~:text=VP6000%20Portable-,VP600%20Portable,-5100%20Portable

Good to have that feedback that that error occurs in the wild.
